version: '3.1'

services:
  nginx:
    image: nginx:1.27.2
    environment:
      TZ: "GMT+12"
      NGINX_HOST: localhost
      NGINX_PORT: 8081
    ports:
      - '80:80'
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    extra_hosts:
      - host.docker.internal:host-gateway
  postgres:
    image: postgres:16.2
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    ports:
      - '5433:5432'
    command: "postgres -c shared_preload_libraries='pg_stat_statements'"
    volumes:
      - 'postgres12-test:/var/lib/postgresql/data'
      - './docker/postgres:/docker-entrypoint-initdb.d'
  pgadmin:
    image: dpage/pgadmin4:2024-10-15-1
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_DISABLE_POSTFIX: 'any value will prevent postfix from starting'
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - '15432:80'
    volumes:
      - './docker/pgadmin/servers.json:/pgadmin4/servers.json'
    depends_on:
      - postgres

volumes:
  postgres12-test:
    driver: local