name: Java CI with Maven

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16.2
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: astraeus_test_db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 23
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B clean verify --file server/pom.xml
        env:
          TEST_DATABASE_JDBC: jdbc:postgresql://localhost:5432/%s?user=postgres&password=postgres